-- MySQL Script generated by MySQL Workbench
-- Thu Apr 17 12:32:06 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dungeons_and_databases
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dungeons_and_databases` ;

-- -----------------------------------------------------
-- Schema dungeons_and_databases
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dungeons_and_databases` DEFAULT CHARACTER SET utf8 ;
USE `dungeons_and_databases` ;

-- -----------------------------------------------------
-- Table `dungeons_and_databases`.`notes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dungeons_and_databases`.`notes` ;

CREATE TABLE IF NOT EXISTS dungeons_and_databases.notes (
  `notes_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(128) NOT NULL,
  `description` TEXT NOT NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (notes_id)
) ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `dungeons_and_databases`.`money`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dungeons_and_databases`.`money` ;

CREATE TABLE IF NOT EXISTS `dungeons_and_databases`.`money` (
  `money_id` INT NOT NULL DEFAULT 0,
  `platinum` INT NULL DEFAULT 0,
  `gold` INT NULL DEFAULT 0,
  `silver` INT NULL DEFAULT 0,
  `copper` INT NULL DEFAULT 0,
  PRIMARY KEY (`money_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dungeons_and_databases`.`stats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dungeons_and_databases`.`stats` ;

CREATE TABLE IF NOT EXISTS `dungeons_and_databases`.`stats` (
  `stats_id` INT NOT NULL AUTO_INCREMENT,
  `Dexterity` INT NULL,
  `Intelligence` INT NULL,
  `Strength` INT NULL,
  `Charisma` INT NULL,
  `Constitution` INT NULL,
  `Wisdom` INT NULL,
  PRIMARY KEY (`stats_id`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dungeons_and_databases`.`species_feature`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dungeons_and_databases`.`species_feature` ;

CREATE TABLE IF NOT EXISTS `dungeons_and_databases`.`species_feature` (
  `species_feature_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`species_feature_id`)
  ) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dungeons_and_databases`.`species`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dungeons_and_databases`.`species` ;

CREATE TABLE IF NOT EXISTS `dungeons_and_databases`.`species` (
  `species_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `creature_type` VARCHAR(45) NOT NULL,
  `size` VARCHAR(45) NOT NULL,
  `speed` VARCHAR(45) NOT NULL,
  `darkvision` TINYINT NOT NULL,
  `species_feature_id` INT NOT NULL,
  PRIMARY KEY (`species_id`),
  INDEX `fk_species_species_feature1_idx` (`species_feature_id` ASC) VISIBLE,
  CONSTRAINT `fk_species_species_feature1`
    FOREIGN KEY (`species_feature_id`)
    REFERENCES `dungeons_and_databases`.`species_feature` (`species_feature_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dungeons_and_databases`.`class_feature`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dungeons_and_databases`.`class_feature` ;

CREATE TABLE IF NOT EXISTS `dungeons_and_databases`.`class_feature` (
  `class_feature_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `level` INT NOT NULL,
  PRIMARY KEY (`class_feature_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dungeons_and_databases`.`class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dungeons_and_databases`.`class` ;

CREATE TABLE IF NOT EXISTS `dungeons_and_databases`.`class` (
  `class_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `hit_die` VARCHAR(10) NOT NULL,
  `main_stat` VARCHAR(20) NOT NULL,
  `caster` TINYINT NOT NULL,
  `saving_throw_proficiencies` VARCHAR(45) NOT NULL,
  `tool_proficiencies` VARCHAR(45) NULL,
  `weapon_proficiencies` VARCHAR(45) NULL,
  `skill_proficiencies` VARCHAR(45) NULL,
  `armor_training` VARCHAR(45) NULL,
  `class_feature_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`class_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_class_class_feature1_idx` (`class_feature_id` ASC) VISIBLE,
  CONSTRAINT `fk_class_class_feature1`
    FOREIGN KEY (`class_feature_id`)
    REFERENCES `dungeons_and_databases`.`class_feature` (`class_feature_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `dungeons_and_databases`.`skill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dungeons_and_databases`.`skill` ;

CREATE TABLE IF NOT EXISTS `dungeons_and_databases`.`skill` (
  `skill_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `associated_stat` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`skill_id`))
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `dungeons_and_databases`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dungeons_and_databases`.`item` ;

CREATE TABLE IF NOT EXISTS `dungeons_and_databases`.`item` (
  `item_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `value` INT NOT NULL,
  `type` ENUM("weapon", "consumable", "armor", "tool", "wondrous", "instrument", "staff") NOT NULL,
  `quantity` INT NULL DEFAULT 1,
  `rarity` ENUM("common", "uncommon", "rare", "very rare", "legendary", "artifact") NULL,
  `magic` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`item_id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `dungeons_and_databases`.`character`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dungeons_and_databases`.`character` ;

CREATE TABLE IF NOT EXISTS `dungeons_and_databases`.`character` (
  `character_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  `alignment` VARCHAR(45) NOT NULL,
  `level` INT NOT NULL,
  `money_id` INT NOT NULL,
  `stats_id` INT NOT NULL,
  `species_id` INT NOT NULL,
  `class_id` INT UNSIGNED NOT NULL,
  `appereance` TEXT NULL,
  `lore` TEXT NULL,
  `personality` TEXT NULL,
  PRIMARY KEY (`character_id`, `money_id`, `stats_id`),
  INDEX `fk_character_money1_idx` (`money_id` ASC) VISIBLE,
  INDEX `fk_character_stats1_idx` (`stats_id` ASC) VISIBLE,
  INDEX `fk_character_species1_idx` (`species_id` ASC) VISIBLE,
  INDEX `fk_character_classes1_idx` (`class_id` ASC) VISIBLE,
  CONSTRAINT `fk_character_money1`
    FOREIGN KEY (`money_id`)
    REFERENCES `dungeons_and_databases`.`money` (`money_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_character_stats1`
    FOREIGN KEY (`stats_id`)
    REFERENCES `dungeons_and_databases`.`stats` (`stats_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_character_species1`
    FOREIGN KEY (`species_id`)
    REFERENCES `dungeons_and_databases`.`species` (`species_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_character_classes1`
    FOREIGN KEY (`class_id`)
    REFERENCES `dungeons_and_databases`.`class` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dungeons_and_databases`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dungeons_and_databases`.`user` ;

CREATE TABLE IF NOT EXISTS `dungeons_and_databases`.`user` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(128) NOT NULL,
  `password` VARCHAR(80) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `first_name` VARCHAR(128) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `role` ENUM("player", "master") NOT NULL,
  `nickname` VARCHAR(128) NOT NULL,
  `character_id` INT UNSIGNED NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `nickname_UNIQUE` (`nickname` ASC) VISIBLE,
  INDEX `fk_user_character1_idx` (`character_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_character1`
    FOREIGN KEY (`character_id`)
    REFERENCES `dungeons_and_databases`.`character` (`character_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `dungeons_and_databases`.`user_has_notes` (
  `user_id` INT UNSIGNED NOT NULL,
  `notes_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `notes_id`),
  INDEX `fk_user_has_notes_notes1_idx` (`notes_id` ASC) VISIBLE,
  INDEX `fk_user_has_notes_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_notes_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `dungeons_and_databases`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_notes_notes1`
    FOREIGN KEY (`notes_id`)
    REFERENCES `dungeons_and_databases`.`notes` (`notes_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `dungeons_and_databases`.`character_has_skill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dungeons_and_databases`.`character_has_skill` ;

CREATE TABLE IF NOT EXISTS `dungeons_and_databases`.`character_has_skill` (
  `character_id` INT UNSIGNED NOT NULL,
  `skill_id` INT NOT NULL,
  `proficiency` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`character_id`, `skill_id`),
  INDEX `fk_character_has_skills_skills1_idx` (`skill_id` ASC) VISIBLE,
  INDEX `fk_character_has_skills_character1_idx` (`character_id` ASC) VISIBLE,
  CONSTRAINT `fk_character_has_skills_character1`
    FOREIGN KEY (`character_id`)
    REFERENCES `dungeons_and_databases`.`character` (`character_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_character_has_skills_skills1`
    FOREIGN KEY (`skill_id`)
    REFERENCES `dungeons_and_databases`.`skill` (`skill_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dungeons_and_databases`.`character_has_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dungeons_and_databases`.`character_has_item` ;

CREATE TABLE IF NOT EXISTS `dungeons_and_databases`.`character_has_item` (
  `character_id` INT UNSIGNED NOT NULL,
  `item_id` INT UNSIGNED NOT NULL, 
  `quantity` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`character_id`, `item_id`),
  INDEX `fk_character_has_item_item1_idx` (`item_id` ASC) VISIBLE,
  INDEX `fk_character_has_item_character1_idx` (`character_id` ASC) VISIBLE,
  CONSTRAINT `fk_character_has_item_character1`
    FOREIGN KEY (`character_id`)
    REFERENCES `dungeons_and_databases`.`character` (`character_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_character_has_item_item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `dungeons_and_databases`.`item` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

